# Generated by Django 4.2.6 on 2023-11-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_productos_cantidad_productos_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='total',
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
