# Generated by Django 4.2.6 on 2023-11-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_promos_delete_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promos',
            name='MixAndTry',
        ),
        migrations.RemoveField(
            model_name='promos',
            name='SalmonLover',
        ),
    ]
