# Generated by Django 4.2.6 on 2023-11-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0006_remove_promos_mixandtry_remove_promos_salmonlover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promos',
            old_name='CantidadM',
            new_name='Cantidad',
        ),
        migrations.RemoveField(
            model_name='promos',
            name='CantidadS',
        ),
        migrations.AddField(
            model_name='promos',
            name='Promo',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
    ]
