# Generated by Django 4.2.6 on 2023-11-18 19:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0011_remove_productos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
