# Generated by Django 4.2.6 on 2023-11-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0014_productos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=30),
        ),
    ]
