# Generated by Django 4.2.6 on 2023-11-18 19:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0016_remove_productos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
