# Generated by Django 4.2.6 on 2023-11-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=30)),
                ('Sabor', models.CharField(max_length=30)),
                ('Adic_ingre', models.CharField(max_length=250)),
                ('Cantidad', models.CharField(max_length=30)),
            ],
        ),
    ]
